CREATE TABLE Articles(
	articleId INTEGER PRIMARY KEY AUTOINCREMENT,
	articleTitle TEXT NOT NULL,
	articleDescription TEXT NOT NULL,
	articleBody TEXT NOT NULL,
	iconCssClass TEXT NOT NULL,
	authorId INTEGER NOT NULL,
	createdDate TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedDate TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);